(()=>{
const languages={en:'English',zh:'简体中文',ja:'日本語'};
const dict={
zh:{
'Event Types':'活动类型','Plan':'策划','Karaoke':'卡拉OK','Gear Hire':'设备租赁','Virtual Setup':'虚拟布置','Enquire':'咨询','Why Ozzsound':'为什么选择 Ozzsound','Check My Date':'查看日期','Events':'活动','Professional DJ & event entertainment · Tasmania':'专业 DJ 与活动娱乐 · 塔斯马尼亚','Your event deserves':'您的活动值得拥有','more than a playlist.':'不止是一份歌单。','Professional DJ and event entertainment shaped around your crowd, your venue and the atmosphere you want to create.':'根据您的宾客、场地和理想氛围量身打造专业 DJ 与活动娱乐。','Explore events':'浏览活动','Ozzsound · Tasmania-wide':'Ozzsound · 服务全塔斯马尼亚','Scroll':'向下浏览','Choose your experience':'选择您的体验','What are you':'您在庆祝','celebrating?':'什么？','Find your event, then make it yours.':'找到适合的活动，再打造属于您的体验。','The Ozzsound experience':'Ozzsound 体验','More than someone':'不只是有人','pressing play.':'按下播放键。','Music, atmosphere and entertainment built around the people in the room.':'音乐、氛围与娱乐，都围绕现场宾客打造。','Make it yours':'打造专属体验','Build the night':'按照您的方式','your way.':'打造这个夜晚。','Hosted entertainment':'主持式娱乐','Equipment':'设备','Planning tool':'策划工具','Build your night →':'打造您的夜晚 →','Choose your gear →':'选择设备 →','See your setup →':'查看布置 →','Availability':'档期','Have a date':'已经有日期','in mind?':'了吗？',"Choose your date and get a quick indication of Ozzsound's availability. If it looks good, you can enquire straight away.":'选择日期即可快速查看 Ozzsound 的档期。如合适，可立即发送咨询。','Availability guide':'档期说明','Available':'可预订','Available from time':'指定时间后可预订','Limited / enquire':'有限 / 请咨询','Unavailable':'不可预订','Booked':'已预订','Select a date':'选择日期','Pick a future date above to check availability.':'请在上方选择未来日期查看档期。','Enquire about this date →':'咨询此日期 →','Ready when you are':'随时为您准备','Tell us about':'告诉我们','your event.':'您的活动。',"Have a date or an idea in mind? Send Ozzsound the details and we'll take it from there.":'已经有日期或想法？把活动详情发给 Ozzsound，接下来交给我们。','Start your enquiry':'开始咨询','DJ & event entertainment':'DJ 与活动娱乐','Tasmania-wide':'服务全塔斯马尼亚','Privacy':'隐私','Admin Login':'管理员登录','Wedding entertainment':'婚礼娱乐','Weddings':'婚礼','Private events':'私人活动','Birthdays & Parties':'生日与派对','Schools & students':'学校与学生','School Functions':'学校活动','Halloween, Christmas & more':'万圣节、圣诞节及更多','Seasonal Events':'节庆活动','Business':'商务活动','Corporate':'企业活动','Clubs & teams':'俱乐部与团队','Sporting Events':'体育活动','Something different':'其他活动','Your Event':'您的活动','Explore →':'了解更多 →','Enquire →':'咨询 →','Tell us →':'告诉我们 →','Drag or swipe to explore':'拖动或滑动浏览'},
ja:{
'Event Types':'イベント','Plan':'プラン','Karaoke':'カラオケ','Gear Hire':'機材レンタル','Virtual Setup':'バーチャルセットアップ','Enquire':'お問い合わせ','Why Ozzsound':'Ozzsoundについて','Check My Date':'日程を確認','Events':'イベント','Professional DJ & event entertainment · Tasmania':'プロDJ・イベントエンターテインメント · タスマニア','Your event deserves':'あなたのイベントには','more than a playlist.':'プレイリスト以上の体験を。','Professional DJ and event entertainment shaped around your crowd, your venue and the atmosphere you want to create.':'ゲスト、会場、理想の雰囲気に合わせたプロDJとイベントエンターテインメント。','Explore events':'イベントを見る','Ozzsound · Tasmania-wide':'Ozzsound · タスマニア全域対応','Scroll':'スクロール','Choose your experience':'体験を選ぶ','What are you':'どんなイベントを','celebrating?':'お祝いしますか？','Find your event, then make it yours.':'イベントを選んで、あなたらしい一日に。','The Ozzsound experience':'Ozzsoundの体験','More than someone':'ただ音楽を','pressing play.':'流すだけではありません。','Music, atmosphere and entertainment built around the people in the room.':'その場にいる人たちを中心に、音楽・雰囲気・エンターテインメントを作ります。','Make it yours':'あなたらしく','Build the night':'理想の夜を','your way.':'あなたのスタイルで。','Hosted entertainment':'ホスト付きエンターテインメント','Equipment':'機材','Planning tool':'プランニングツール','Build your night →':'夜をプランする →','Choose your gear →':'機材を選ぶ →','See your setup →':'セットアップを見る →','Availability':'空き状況','Have a date':'希望日は','in mind?':'ありますか？',"Choose your date and get a quick indication of Ozzsound's availability. If it looks good, you can enquire straight away.":'日付を選ぶとOzzsoundの空き状況をすぐ確認できます。空いていればそのままお問い合わせいただけます。','Availability guide':'空き状況ガイド','Available':'空きあり','Available from time':'指定時刻以降空きあり','Limited / enquire':'要相談','Unavailable':'対応不可','Booked':'予約済み','Select a date':'日付を選択','Pick a future date above to check availability.':'上から今後の日付を選んで空き状況をご確認ください。','Enquire about this date →':'この日程を問い合わせる →','Ready when you are':'準備ができたら','Tell us about':'イベントについて','your event.':'お聞かせください。',"Have a date or an idea in mind? Send Ozzsound the details and we'll take it from there.":'日程やアイデアが決まっていれば、詳細をOzzsoundへ。あとは私たちがお手伝いします。','Start your enquiry':'問い合わせを始める','DJ & event entertainment':'DJ・イベントエンターテインメント','Tasmania-wide':'タスマニア全域対応','Privacy':'プライバシー','Admin Login':'管理者ログイン','Wedding entertainment':'ウェディング','Weddings':'ウェディング','Private events':'プライベートイベント','Birthdays & Parties':'誕生日・パーティー','Schools & students':'学校・学生','School Functions':'学校イベント','Halloween, Christmas & more':'ハロウィン、クリスマスなど','Seasonal Events':'季節イベント','Business':'ビジネス','Corporate':'企業イベント','Clubs & teams':'クラブ・チーム','Sporting Events':'スポーツイベント','Something different':'その他','Your Event':'あなたのイベント','Explore →':'詳しく見る →','Enquire →':'問い合わせ →','Tell us →':'相談する →','Drag or swipe to explore':'ドラッグまたはスワイプして見る'}
};
const norm=s=>String(s||'').replace(/\s+/g,' ').trim();
const extra={
zh:{'Your name *':'您的姓名 *','Phone *':'电话 *','Email':'电子邮箱','Event type *':'活动类型 *','Choose event type':'选择活动类型','Wedding':'婚礼','Birthday & Party':'生日与派对','School Function':'学校活动','Seasonal Event':'节庆活动','Corporate Event':'企业活动','Sporting Event':'体育活动','Other Event':'其他活动','Event date *':'活动日期 *','Venue / suburb *':'场地 / 区域 *','Approx. guests':'预计宾客人数','Start time *':'开始时间 *','Finish time *':'结束时间 *','Anything else we should know?':'还有什么需要我们了解？','Send enquiry':'发送咨询','Your day. Your music.':'您的婚礼，您的音乐。','Start with the big picture.':'先从整体开始。','Wedding date':'婚礼日期','Where is it happening?':'活动在哪里举行？','Indoor':'室内','Outdoor':'室外','Indoor & outdoor':'室内及室外','Ceremony':'仪式','Reception':'婚宴','The whole day':'全天','Shape the ceremony.':'规划您的仪式。','Build your':'打造您的','karaoke night.':'卡拉OK之夜。','Choose your eras':'选择年代','Choose your styles':'选择音乐风格','What kind of event?':'什么类型的活动？','gear hire.':'设备租赁。','All gear':'全部设备','Sound':'音响','Lighting':'灯光','Microphones':'麦克风','DJ gear':'DJ设备','Build your package':'创建您的设备组合','Clear list':'清空列表','Event / hire date':'活动 / 租赁日期','See it before we':'提前预览','Planning tool only.':'仅供策划参考。','1. Your space':'1. 您的场地','2. Add equipment':'2. 添加设备','3. Build your setup':'3. 创建布置','Upload a photo to begin':'上传照片开始','Duplicate':'复制','Remove':'移除','Clear setup':'清空布置','Save preview image':'保存预览图','Built around your event':'围绕您的活动打造','As formal or as fun as you want':'正式或欢乐，由您决定','Planning beyond the playlist':'不止是歌单的策划','Ready to plan yours?':'准备开始策划了吗？','Your gear hire':'您的设备租赁','Your karaoke':'您的卡拉OK','Choose one':'请选择','1 day':'1天','2 days':'2天','3 days':'3天','Weekend':'周末'},
ja:{'Your name *':'お名前 *','Phone *':'電話番号 *','Email':'メール','Event type *':'イベント種別 *','Choose event type':'イベントを選択','Wedding':'ウェディング','Birthday & Party':'誕生日・パーティー','School Function':'学校イベント','Seasonal Event':'季節イベント','Corporate Event':'企業イベント','Sporting Event':'スポーツイベント','Other Event':'その他','Event date *':'開催日 *','Venue / suburb *':'会場 / エリア *','Approx. guests':'予定人数','Start time *':'開始時間 *','Finish time *':'終了時間 *','Anything else we should know?':'その他のご希望','Send enquiry':'問い合わせを送る','Your day. Your music.':'あなたの日。あなたの音楽。','Start with the big picture.':'まずは全体像から。','Wedding date':'結婚式の日付','Where is it happening?':'会場はどこですか？','Indoor':'屋内','Outdoor':'屋外','Indoor & outdoor':'屋内・屋外','Ceremony':'挙式','Reception':'披露宴','The whole day':'一日を通して','Shape the ceremony.':'挙式をプラン。','Build your':'あなたの','karaoke night.':'カラオケナイトを。','Choose your eras':'年代を選ぶ','Choose your styles':'音楽スタイルを選ぶ','What kind of event?':'イベントの種類は？','gear hire.':'機材レンタル。','All gear':'すべての機材','Sound':'音響','Lighting':'照明','Microphones':'マイク','DJ gear':'DJ機材','Build your package':'レンタル内容を作る','Clear list':'リストをクリア','Event / hire date':'イベント / レンタル日','See it before we':'事前にイメージ','Planning tool only.':'プランニング専用ツールです。','1. Your space':'1. 会場','2. Add equipment':'2. 機材を追加','3. Build your setup':'3. セットアップを作成','Upload a photo to begin':'写真をアップロードして開始','Duplicate':'複製','Remove':'削除','Clear setup':'セットアップをクリア','Save preview image':'プレビュー画像を保存','Built around your event':'イベントに合わせて','As formal or as fun as you want':'フォーマルにも楽しくも','Planning beyond the playlist':'プレイリスト以上のプランニング','Ready to plan yours?':'イベントを計画しませんか？','Your gear hire':'機材レンタル','Your karaoke':'カラオケ','Choose one':'選択してください','1 day':'1日','2 days':'2日','3 days':'3日','Weekend':'週末'}};
Object.assign(dict.zh,extra.zh);Object.assign(dict.ja,extra.ja);
function apply(lang){
 document.documentElement.lang=lang==='zh'?'zh-CN':lang;
 document.querySelectorAll('[data-i18n-original]').forEach(el=>{el.textContent=el.dataset.i18nOriginal});
 if(lang!=='en'){
  const d=dict[lang]||{};
  document.querySelectorAll('a,button,small,strong,p,h1,h2,h3,label>span,option,.eyebrow,.heroStatus span:last-child,.scrollCue span,.footerTagline,.mobileMenuFoot,summary').forEach(el=>{
   if(el.children.length&&![...el.children].every(x=>x.tagName==='SPAN'))return;
   const key=norm(el.dataset.i18nOriginal||el.textContent);
   if(!el.dataset.i18nOriginal)el.dataset.i18nOriginal=key;
   if(d[key])el.textContent=d[key];
  });
 }
 document.querySelectorAll('[data-lang-current]').forEach(x=>x.textContent=lang.toUpperCase());
 localStorage.setItem('ozzsoundLanguage',lang);
 document.querySelectorAll('[data-lang]').forEach(x=>x.setAttribute('aria-current',x.dataset.lang===lang?'true':'false'));
}
function mount(){
 if(document.querySelector('.languagePicker'))return;
 const picker=document.createElement('div');picker.className='languagePicker';
 picker.innerHTML='<button class="languageButton" type="button" aria-label="Choose language" aria-expanded="false">🌐 <span data-lang-current>EN</span> <i>⌄</i></button><div class="languageMenu">'+Object.entries(languages).map(([k,v])=>'<button type="button" data-lang="'+k+'"><span>'+v+'</span><small>'+k.toUpperCase()+'</small></button>').join('')+'</div>';
 const nav=document.querySelector('.navlinks');if(nav)nav.insertBefore(picker,nav.querySelector('.navCta'));
 const mobile=document.querySelector('.mobileMenuInner');if(mobile){const m=picker.cloneNode(true);m.classList.add('languagePickerMobile');mobile.appendChild(m);}
 document.querySelectorAll('.languagePicker').forEach(p=>{const b=p.querySelector('.languageButton');b.addEventListener('click',()=>{const open=p.classList.toggle('open');b.setAttribute('aria-expanded',String(open));});p.querySelectorAll('[data-lang]').forEach(x=>x.addEventListener('click',()=>{apply(x.dataset.lang);document.querySelectorAll('.languagePicker').forEach(q=>q.classList.remove('open'));}));});
 apply(localStorage.getItem('ozzsoundLanguage')||'en');
}
document.addEventListener('DOMContentLoaded',mount);
})();