(()=>{
const languages={en:'English',zh:'简体中文',ja:'日本語'};
const dict={
zh:{
'Event Types':'活动类型','Plan':'策划','Karaoke':'卡拉OK','Gear Hire':'设备租赁','Virtual Setup':'虚拟布置','Enquire':'咨询','Why Ozzsound':'为什么选择 Ozzsound','Check My Date':'查看日期','Events':'活动','Professional DJ & event entertainment · Tasmania':'专业 DJ 与活动娱乐 · 塔斯马尼亚','Your event deserves':'您的活动值得拥有','more than a playlist.':'不止是一份歌单。','Professional DJ and event entertainment shaped around your crowd, your venue and the atmosphere you want to create.':'根据您的宾客、场地和理想氛围量身打造专业 DJ 与活动娱乐。','Explore events':'浏览活动','Ozzsound · Tasmania-wide':'Ozzsound · 服务全塔斯马尼亚','Scroll':'向下浏览','Choose your experience':'选择您的体验','What are you':'您在庆祝','celebrating?':'什么？','Find your event, then make it yours.':'找到适合的活动，再打造属于您的体验。','The Ozzsound experience':'Ozzsound 体验','More than someone':'不只是有人','pressing play.':'按下播放键。','Music, atmosphere and entertainment built around the people in the room.':'音乐、氛围与娱乐，都围绕现场宾客打造。','Make it yours':'打造专属体验','Build the night':'按照您的方式','your way.':'打造这个夜晚。','Hosted entertainment':'主持式娱乐','Equipment':'设备','Planning tool':'策划工具','Build your night →':'打造您的夜晚 →','Choose your gear →':'选择设备 →','See your setup →':'查看布置 →','Availability':'档期','Have a date':'已经有日期','in mind?':'了吗？',"Choose your date and get a quick indication of Ozzsound's availability. If it looks good, you can enquire straight away.":'选择日期即可快速查看 Ozzsound 的档期。如合适，可立即发送咨询。','Availability guide':'档期说明','Available':'可预订','Available from time':'指定时间后可预订','Limited / enquire':'有限 / 请咨询','Unavailable':'不可预订','Booked':'已预订','Select a date':'选择日期','Pick a future date above to check availability.':'请在上方选择未来日期查看档期。','Enquire about this date →':'咨询此日期 →','Ready when you are':'随时为您准备','Tell us about':'告诉我们','your event.':'您的活动。',"Have a date or an idea in mind? Send Ozzsound the details and we'll take it from there.":'已经有日期或想法？把活动详情发给 Ozzsound，接下来交给我们。','Start your enquiry':'开始咨询','DJ & event entertainment':'DJ 与活动娱乐','Tasmania-wide':'服务全塔斯马尼亚','Privacy':'隐私','Admin Login':'管理员登录','Wedding entertainment':'婚礼娱乐','Weddings':'婚礼','Private events':'私人活动','Birthdays & Parties':'生日与派对','Schools & students':'学校与学生','School Functions':'学校活动','Halloween, Christmas & more':'万圣节、圣诞节及更多','Seasonal Events':'节庆活动','Business':'商务活动','Corporate':'企业活动','Clubs & teams':'俱乐部与团队','Sporting Events':'体育活动','Something different':'其他活动','Your Event':'您的活动','Explore →':'了解更多 →','Enquire →':'咨询 →','Tell us →':'告诉我们 →','Drag or swipe to explore':'拖动或滑动浏览'},
ja:{
'Event Types':'イベント','Plan':'プラン','Karaoke':'カラオケ','Gear Hire':'機材レンタル','Virtual Setup':'バーチャルセットアップ','Enquire':'お問い合わせ','Why Ozzsound':'Ozzsoundについて','Check My Date':'日程を確認','Events':'イベント','Professional DJ & event entertainment · Tasmania':'プロDJ・イベントエンターテインメント · タスマニア','Your event deserves':'あなたのイベントには','more than a playlist.':'プレイリスト以上の体験を。','Professional DJ and event entertainment shaped around your crowd, your venue and the atmosphere you want to create.':'ゲスト、会場、理想の雰囲気に合わせたプロDJとイベントエンターテインメント。','Explore events':'イベントを見る','Ozzsound · Tasmania-wide':'Ozzsound · タスマニア全域対応','Scroll':'スクロール','Choose your experience':'体験を選ぶ','What are you':'どんなイベントを','celebrating?':'お祝いしますか？','Find your event, then make it yours.':'イベントを選んで、あなたらしい一日に。','The Ozzsound experience':'Ozzsoundの体験','More than someone':'ただ音楽を','pressing play.':'流すだけではありません。','Music, atmosphere and entertainment built around the people in the room.':'その場にいる人たちを中心に、音楽・雰囲気・エンターテインメントを作ります。','Make it yours':'あなたらしく','Build the night':'理想の夜を','your way.':'あなたのスタイルで。','Hosted entertainment':'ホスト付きエンターテインメント','Equipment':'機材','Planning tool':'プランニングツール','Build your night →':'夜をプランする →','Choose your gear →':'機材を選ぶ →','See your setup →':'セットアップを見る →','Availability':'空き状況','Have a date':'希望日は','in mind?':'ありますか？',"Choose your date and get a quick indication of Ozzsound's availability. If it looks good, you can enquire straight away.":'日付を選ぶとOzzsoundの空き状況をすぐ確認できます。空いていればそのままお問い合わせいただけます。','Availability guide':'空き状況ガイド','Available':'空きあり','Available from time':'指定時刻以降空きあり','Limited / enquire':'要相談','Unavailable':'対応不可','Booked':'予約済み','Select a date':'日付を選択','Pick a future date above to check availability.':'上から今後の日付を選んで空き状況をご確認ください。','Enquire about this date →':'この日程を問い合わせる →','Ready when you are':'準備ができたら','Tell us about':'イベントについて','your event.':'お聞かせください。',"Have a date or an idea in mind? Send Ozzsound the details and we'll take it from there.":'日程やアイデアが決まっていれば、詳細をOzzsoundへ。あとは私たちがお手伝いします。','Start your enquiry':'問い合わせを始める','DJ & event entertainment':'DJ・イベントエンターテインメント','Tasmania-wide':'タスマニア全域対応','Privacy':'プライバシー','Admin Login':'管理者ログイン','Wedding entertainment':'ウェディング','Weddings':'ウェディング','Private events':'プライベートイベント','Birthdays & Parties':'誕生日・パーティー','Schools & students':'学校・学生','School Functions':'学校イベント','Halloween, Christmas & more':'ハロウィン、クリスマスなど','Seasonal Events':'季節イベント','Business':'ビジネス','Corporate':'企業イベント','Clubs & teams':'クラブ・チーム','Sporting Events':'スポーツイベント','Something different':'その他','Your Event':'あなたのイベント','Explore →':'詳しく見る →','Enquire →':'問い合わせ →','Tell us →':'相談する →','Drag or swipe to explore':'ドラッグまたはスワイプして見る'}
};
const norm=s=>String(s||'').replace(/\s+/g,' ').trim();
function apply(lang){
 document.documentElement.lang=lang==='zh'?'zh-CN':lang;
 document.querySelectorAll('[data-i18n-original]').forEach(el=>{el.textContent=el.dataset.i18nOriginal});
 if(lang!=='en'){
  const d=dict[lang]||{};
  document.querySelectorAll('a,button,small,strong,p,h1,h2,h3,.eyebrow,.heroStatus span:last-child,.scrollCue span,.footerTagline,.mobileMenuFoot,summary').forEach(el=>{
   if(el.children.length&&![...el.children].every(x=>x.tagName==='SPAN'))return;
   const key=norm(el.dataset.i18nOriginal||el.textContent);
   if(!el.dataset.i18nOriginal)el.dataset.i18nOriginal=key;
   if(d[key])el.textContent=d[key];
  });
 }
 document.querySelectorAll('[data-lang-current]').forEach(x=>x.textContent=lang.toUpperCase());
 localStorage.setItem('ozzsoundLanguage',lang);
 document.querySelectorAll('[data-lang]').forEach(x=>x.setAttribute('aria-current',x.dataset.lang===lang?'true':'false'));
}
function mount(){
 if(document.querySelector('.languagePicker'))return;
 const picker=document.createElement('div');picker.className='languagePicker';
 picker.innerHTML='<button class="languageButton" type="button" aria-label="Choose language" aria-expanded="false">🌐 <span data-lang-current>EN</span> <i>⌄</i></button><div class="languageMenu">'+Object.entries(languages).map(([k,v])=>'<button type="button" data-lang="'+k+'"><span>'+v+'</span><small>'+k.toUpperCase()+'</small></button>').join('')+'</div>';
 const nav=document.querySelector('.navlinks');if(nav)nav.insertBefore(picker,nav.querySelector('.navCta'));
 const mobile=document.querySelector('.mobileMenuInner');if(mobile){const m=picker.cloneNode(true);m.classList.add('languagePickerMobile');mobile.appendChild(m);}
 document.querySelectorAll('.languagePicker').forEach(p=>{const b=p.querySelector('.languageButton');b.addEventListener('click',()=>{const open=p.classList.toggle('open');b.setAttribute('aria-expanded',String(open));});p.querySelectorAll('[data-lang]').forEach(x=>x.addEventListener('click',()=>{apply(x.dataset.lang);document.querySelectorAll('.languagePicker').forEach(q=>q.classList.remove('open'));}));});
 apply(localStorage.getItem('ozzsoundLanguage')||'en');
}
document.addEventListener('DOMContentLoaded',mount);
})();