(()=>{
const form=document.querySelector('#partyBuilder');if(!form)return;
const steps=[...document.querySelectorAll('.partyStep')],bars=[...document.querySelectorAll('.partyProgress span')],prev=document.querySelector('#partyPrev'),next=document.querySelector('#partyNext'),funBox=document.querySelector('#funBox'),strobeApproval=document.querySelector('#strobeApproval'),summaryBox=document.querySelector('#partySummary');
let step=0;const state={type:'',vibe:'',crowd:'',musicControl:'',strobe:'',strobeApproval:'',music:new Set(),moments:new Set(),fun:new Set()};
const today=new Date();form.elements.date.min=`${today.getFullYear()}-${String(today.getMonth()+1).padStart(2,'0')}-${String(today.getDate()).padStart(2,'0')}`;
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const showFun=()=>state.type==="Kids' Birthday"||state.type==="Teen Birthday"||state.vibe==='Interactive & fun'||state.crowd==='Mostly kids';
function syncConditional(){const visible=showFun();funBox.hidden=!visible;if(!visible){state.fun.clear();funBox.querySelectorAll('.selected').forEach(x=>x.classList.remove('selected'))}strobeApproval.classList.toggle('show',state.strobe==='Yes');if(state.strobe!=='Yes'){state.strobeApproval='';document.querySelectorAll('[data-single="strobeApproval"]').forEach(x=>x.classList.remove('selected'))}}
function data(){return {type:state.type,vibe:state.vibe,crowd:state.crowd,music:[...state.music],musicControl:state.musicControl,moments:[...state.moments],fun:[...state.fun],strobe:state.strobe,strobeApproval:state.strobe==='Yes'?(state.strobeApproval||'Not confirmed'):'Not applicable',date:form.elements.date.value,venue:form.elements.venue.value.trim(),guests:form.elements.guests.value,setting:form.elements.setting.value,notes:form.elements.notes.value.trim()}}
function save(){try{localStorage.setItem('ozzsoundPartyBuilder',JSON.stringify(data()))}catch(e){}}
function restore(){try{const d=JSON.parse(localStorage.getItem('ozzsoundPartyBuilder')||'null');if(!d)return;['type','vibe','crowd','musicControl','strobe','strobeApproval'].forEach(k=>state[k]=d[k]||'');['music','moments','fun'].forEach(k=>state[k]=new Set(Array.isArray(d[k])?d[k]:[]));['date','venue','guests','setting','notes'].forEach(k=>{if(form.elements[k]&&d[k]!=null)form.elements[k].value=d[k]});document.querySelectorAll('[data-single]').forEach(b=>b.classList.toggle('selected',state[b.dataset.single]===b.dataset.value));document.querySelectorAll('[data-multi]').forEach(b=>b.classList.toggle('selected',state[b.dataset.multi]?.has(b.dataset.value)));syncConditional()}catch(e){}}
function summary(){const d=data(),items=[['Party',d.type||'Not chosen yet'],['Feel',d.vibe||'Not chosen yet']];if(d.crowd)items.push(['Crowd',d.crowd]);if(d.date)items.push(['Date',d.date]);if(d.venue)items.push(['Venue',d.venue]);if(d.guests)items.push(['Guests','Approx. '+d.guests]);if(d.music.length)items.push(['Music',d.music.join(', ')]);if(d.musicControl)items.push(['Music approach',d.musicControl]);if(d.moments.length)items.push(['Important bits',d.moments.join(', ')]);if(d.fun.length)items.push(['Fun options',d.fun.join(', ')]);if(d.strobe)items.push(['Strobe',d.strobe+(d.strobe==='Yes'?' · '+d.strobeApproval:'')]);summaryBox.innerHTML=items.map(([a,b])=>`<div class="summaryCard"><small>${esc(a)}</small><strong>${esc(b)}</strong></div>`).join('')}
document.addEventListener('click',e=>{const b=e.target.closest('[data-single],[data-multi]');if(!b||!form.contains(b))return;if(b.dataset.single){const k=b.dataset.single;state[k]=state[k]===b.dataset.value?'':b.dataset.value;document.querySelectorAll('[data-single="'+k+'"]').forEach(x=>x.classList.toggle('selected',x.dataset.value===state[k]))}else{const set=state[b.dataset.multi],v=b.dataset.value;set.has(v)?set.delete(v):set.add(v);b.classList.toggle('selected',set.has(v))}syncConditional();save();summary()});
form.addEventListener('input',()=>{save();summary()});form.addEventListener('change',()=>{save();summary()});
function show(n,scroll=true){step=Math.max(0,Math.min(steps.length-1,n));steps.forEach((x,i)=>x.classList.toggle('active',i===step));bars.forEach((x,i)=>x.classList.toggle('on',i<=step));prev.style.visibility=step?'visible':'hidden';next.innerHTML=step===steps.length-1?'Continue to enquiry <span>→</span>':'Next <span>→</span>';if(step===steps.length-1)summary();if(scroll)window.scrollTo({top:Math.max(0,document.querySelector('.partyProgress').offsetTop-115),behavior:'smooth'})}
prev.addEventListener('click',()=>show(step-1));next.addEventListener('click',()=>{if(step<steps.length-1)return show(step+1);save();location.href='event-enquiry.html?event=Birthday%20%26%20Party&from=party'});
restore();summary();show(0,false);
})();