(()=>{
const form=document.querySelector('#partyBuilder');if(!form)return;
const steps=[...document.querySelectorAll('.partyStep')],bars=[...document.querySelectorAll('.partyProgress span')],prev=document.querySelector('#partyPrev'),next=document.querySelector('#partyNext'),kids=document.querySelector('#kidsOptions'),strobeBox=document.querySelector('#strobeApproval');
let step=0;const state={type:'',vibe:'',crowd:'',kidsLevel:'',musicControl:'',strobe:'',strobeApproval:'',involvement:new Set(),fun:new Set(),music:new Set(),moments:new Set()};
const today=new Date();form.elements.date.min=`${today.getFullYear()}-${String(today.getMonth()+1).padStart(2,'0')}-${String(today.getDate()).padStart(2,'0')}`;
const isKids=()=>state.type==="Kids' Birthday";
function syncConditional(){kids.classList.toggle('show',isKids());if(!isKids()){state.kidsLevel='';state.fun.clear();document.querySelectorAll('#kidsOptions .selected').forEach(x=>x.classList.remove('selected'))}strobeBox.classList.toggle('show',state.strobe==='Yes');if(state.strobe!=='Yes'){state.strobeApproval='';document.querySelectorAll('[data-single="strobeApproval"]').forEach(x=>x.classList.remove('selected'))}}
function save(){const d=data();try{localStorage.setItem('ozzsoundPartyBuilder',JSON.stringify(d))}catch(e){}}
function data(){return {type:state.type,vibe:state.vibe,crowd:state.crowd,kidsLevel:state.kidsLevel,involvement:[...state.involvement],fun:[...state.fun],music:[...state.music],musicControl:state.musicControl,moments:[...state.moments],strobe:state.strobe,strobeApproval:state.strobe==='Yes'?(state.strobeApproval||'Not confirmed'):'Not applicable',date:form.elements.date.value,venue:form.elements.venue.value.trim(),guests:form.elements.guests.value,setting:form.elements.setting.value,notes:form.elements.notes.value.trim()}}
function restore(){
 try{const d=JSON.parse(localStorage.getItem('ozzsoundPartyBuilder')||'null');if(!d)return;['type','vibe','crowd','kidsLevel','musicControl','strobe','strobeApproval'].forEach(k=>state[k]=d[k]||'');['involvement','fun','music','moments'].forEach(k=>state[k]=new Set(Array.isArray(d[k])?d[k]:[]));['date','venue','guests','setting','notes'].forEach(k=>{if(form.elements[k]&&d[k]!=null)form.elements[k].value=d[k]});document.querySelectorAll('[data-single]').forEach(b=>b.classList.toggle('selected',state[b.dataset.single]===b.dataset.value));document.querySelectorAll('[data-multi]').forEach(b=>b.classList.toggle('selected',state[b.dataset.multi]?.has(b.dataset.value)));syncConditional()}catch(e){}
}
document.addEventListener('click',e=>{const b=e.target.closest('[data-single],[data-multi]');if(!b||!form.contains(b))return;if(b.dataset.single){const key=b.dataset.single;state[key]=state[key]===b.dataset.value?'':b.dataset.value;document.querySelectorAll('[data-single="'+key+'"]').forEach(x=>x.classList.toggle('selected',x.dataset.value===state[key]))}else{const set=state[b.dataset.multi],v=b.dataset.value;set.has(v)?set.delete(v):set.add(v);b.classList.toggle('selected',set.has(v))}syncConditional();save()});
form.addEventListener('input',save);form.addEventListener('change',save);
function summary(){const d=data(),items=[['Celebration',d.type||'Not decided yet'],['Date',d.date||'Not decided yet'],['Venue',d.venue||'Not decided yet'],['Guests',d.guests?'Approx. '+d.guests:'Not decided yet'],['Vibe',d.vibe||'Not decided yet'],['Crowd',d.crowd||'Not decided yet'],['Dazz involved in',d.involvement.join(', ')||'Not specified'],['Music',d.music.join(', ')||'Not specified'],['Music direction',d.musicControl||'Not decided yet'],['Party moments',d.moments.join(', ')||'None selected']];if(d.kidsLevel)items.push(['Kids party style',d.kidsLevel]);if(d.fun.length)items.push(['Fun options',d.fun.join(', ')]);if(d.strobe)items.push(['Strobe',d.strobe+(d.strobe==='Yes'?' · Approval: '+d.strobeApproval:'')]);if(d.notes)items.push(['Anything else',d.notes]);document.querySelector('#partySummary').innerHTML=items.map(([a,b])=>`<div class="summaryCard"><small>${a}</small><strong>${String(b).replace(/</g,'&lt;')}</strong></div>`).join('')}
function show(n,scroll=true){step=Math.max(0,Math.min(steps.length-1,n));steps.forEach((x,i)=>x.classList.toggle('active',i===step));bars.forEach((x,i)=>x.classList.toggle('on',i<=step));prev.style.visibility=step?'visible':'hidden';next.innerHTML=step===steps.length-1?'Continue to party enquiry <span>→</span>':'Next step <span>→</span>';if(step===steps.length-1)summary();if(scroll)window.scrollTo({top:Math.max(0,document.querySelector('.partyProgress').offsetTop-120),behavior:'smooth'})}
prev.addEventListener('click',()=>show(step-1));next.addEventListener('click',()=>{if(step<steps.length-1)return show(step+1);save();location.href='event-enquiry.html?event=Birthday%20%26%20Party&from=party'});
restore();show(0,false);
})();