(()=>{
const form=document.querySelector('#weddingBuilder');if(!form)return;
const steps=[...document.querySelectorAll('.wedStep')],bars=[...document.querySelectorAll('.wedProgress span')],prev=document.querySelector('#wedPrev'),next=document.querySelector('#wedNext');let step=0;
const today=new Date(),date=form.elements.date;date.min=`${today.getFullYear()}-${String(today.getMonth()+1).padStart(2,'0')}-${String(today.getDate()).padStart(2,'0')}`;
function show(n){step=Math.max(0,Math.min(steps.length-1,n));steps.forEach((x,i)=>x.classList.toggle('active',i===step));bars.forEach((x,i)=>x.classList.toggle('on',i<=step));prev.style.visibility=step?'visible':'hidden';next.innerHTML=step===steps.length-1?'Continue to wedding enquiry <span>→</span>':'Next step <span>→</span>';if(step===steps.length-1)summary();window.scrollTo({top:Math.max(0,document.querySelector('.wedProgress').offsetTop-120),behavior:'smooth'});}
function checked(name){return [...form.querySelectorAll(`[name="${name}"]:checked`)].map(x=>x.value)}
function timeline(){return [...document.querySelectorAll('.timelineRow')].map(r=>{const i=r.querySelectorAll('input');return {time:i[0].value,event:i[1].value.trim()}}).filter(x=>x.time||x.event)}
function data(){return {date:form.elements.date.value,venue:form.elements.venue.value.trim(),guests:form.elements.guests.value,setting:form.elements.setting.value,coverage:checked('coverage'),ceremonyNeeds:checked('ceremonyNeeds'),receptionNeeds:checked('receptionNeeds'),style:checked('style')[0]||'',mustPlay:form.elements.mustPlay.value.trim(),wouldLove:form.elements.wouldLove.value.trim(),doNotPlay:form.elements.doNotPlay.value.trim(),extras:checked('extras'),timeline:timeline()}}
function summary(){const d=data(),items=[['Wedding',d.coverage.join(', ')||'Not decided yet'],['Date',d.date||'Not decided yet'],['Venue',d.venue||'Not decided yet'],['Guests',d.guests?`Approx. ${d.guests}`:'Not decided yet'],['Style',d.style||'Not decided yet'],['Extras',d.extras.join(', ')||'None selected'],['Ceremony',d.ceremonyNeeds.join(', ')||'Not specified'],['Reception',d.receptionNeeds.join(', ')||'Not specified']];document.querySelector('#wedSummary').innerHTML=items.map(([a,b])=>`<div class="summaryCard"><small>${a}</small><strong>${b}</strong></div>`).join('')}
prev.addEventListener('click',()=>show(step-1));next.addEventListener('click',()=>{if(step<steps.length-1)return show(step+1);const d=data();localStorage.setItem('ozzsoundWeddingBuilder',JSON.stringify(d));location.href='index.html?from=wedding#contact'});
document.querySelector('#addTimeline').addEventListener('click',()=>{const row=document.createElement('div');row.className='timelineRow';row.innerHTML='<input type="time" aria-label="Timeline time"><input placeholder="e.g. Dance floor opens" aria-label="Timeline event"><button type="button" class="removeRow" aria-label="Remove row">×</button>';document.querySelector('#timeline').appendChild(row)});document.querySelector('#timeline').addEventListener('click',e=>{if(e.target.closest('.removeRow')&&document.querySelectorAll('.timelineRow').length>1)e.target.closest('.timelineRow').remove()});
show(0);
})();
