(()=>{
const form=document.querySelector('#weddingBuilder');if(!form)return;
const steps=[...document.querySelectorAll('.wedStep')],bars=[...document.querySelectorAll('.wedProgress span')],prev=document.querySelector('#wedPrev'),next=document.querySelector('#wedNext');let step=0;
const today=new Date(),date=form.elements.date;date.min=`${today.getFullYear()}-${String(today.getMonth()+1).padStart(2,'0')}-${String(today.getDate()).padStart(2,'0')}`;
const checked=name=>[...form.querySelectorAll(`[name="${name}"]:checked`)].map(x=>x.value);
const esc=v=>(v||'').replace(/&/g,'&amp;').replace(/"/g,'&quot;').replace(/</g,'&lt;');
const songIdeas={
 entrance:[['Signed, Sealed, Delivered','Stevie Wonder'],['Walking on Sunshine','Katrina & The Waves'],['Another One Bites the Dust','Queen'],['From This Moment On','Shania Twain'],['Love and Marriage','Frank Sinatra'],['I Do, I Do, I Do, I Do, I Do','ABBA'],['Can You Feel the Love Tonight','Elton John'],["I'm a Believer",'Smash Mouth'],['Beautiful Day','U2'],["You're the One That I Want",'Grease'],['Chapel of Love','The Dixie Cups'],['Love Today','Mika'],['Love Is in the Air','John Paul Young'],['2 Be Loved','Lizzo']],
 bridal1:[['At Last','Etta James'],['Could I Have This Dance','Anne Murray'],["Can't Help Falling in Love",'Elvis Presley'],['Unchained Melody','The Righteous Brothers'],['Unforgettable','Natalie Cole'],['Everything','Michael Bublé'],['Endless Love','Lionel Richie & Diana Ross'],['Perfect','Ed Sheeran / Beyoncé'],['The Power of Love','Celine Dion'],['A Thousand Years','Christina Perri'],['When a Man Loves a Woman','Percy Sledge'],['Lover','Taylor Swift'],['Amazed','Lonestar'],['Until I Found You','Stephen Sanchez'],['When You Say Nothing at All','Ronan Keating'],['You Are the Reason','Calum Scott'],['I Knew I Loved You','Savage Garden'],['I Get to Love You','Ruelle'],['Truly Madly Deeply','Savage Garden'],['From This Moment On','Shania Twain'],['Have I Told You Lately','Van Morrison'],['Heaven','Bryan Adams'],['Still the One','Shania Twain'],['Because You Loved Me','Celine Dion']],
 bridal2:[['At Last','Etta James'],['Could I Have This Dance','Anne Murray'],["Can't Help Falling in Love",'Elvis Presley'],['Unchained Melody','The Righteous Brothers'],['Unforgettable','Natalie Cole'],['Everything','Michael Bublé'],['Endless Love','Lionel Richie & Diana Ross'],['Perfect','Ed Sheeran / Beyoncé'],['The Power of Love','Celine Dion'],['A Thousand Years','Christina Perri'],['When a Man Loves a Woman','Percy Sledge'],['Lover','Taylor Swift'],['Amazed','Lonestar'],['Until I Found You','Stephen Sanchez'],['When You Say Nothing at All','Ronan Keating'],['You Are the Reason','Calum Scott'],['I Knew I Loved You','Savage Garden'],['I Get to Love You','Ruelle'],['Truly Madly Deeply','Savage Garden'],['From This Moment On','Shania Twain'],['Have I Told You Lately','Van Morrison'],['Heaven','Bryan Adams'],['Still the One','Shania Twain'],['Because You Loved Me','Celine Dion']],
 bridal3:[['At Last','Etta James'],['Could I Have This Dance','Anne Murray'],["Can't Help Falling in Love",'Elvis Presley'],['Unchained Melody','The Righteous Brothers'],['Unforgettable','Natalie Cole'],['Everything','Michael Bublé'],['Endless Love','Lionel Richie & Diana Ross'],['Perfect','Ed Sheeran / Beyoncé'],['The Power of Love','Celine Dion'],['A Thousand Years','Christina Perri'],['When a Man Loves a Woman','Percy Sledge'],['Lover','Taylor Swift'],['Amazed','Lonestar'],['Until I Found You','Stephen Sanchez'],['When You Say Nothing at All','Ronan Keating'],['You Are the Reason','Calum Scott'],['I Knew I Loved You','Savage Garden'],['I Get to Love You','Ruelle'],['Truly Madly Deeply','Savage Garden'],['From This Moment On','Shania Twain'],['Have I Told You Lately','Van Morrison'],['Heaven','Bryan Adams'],['Still the One','Shania Twain'],['Because You Loved Me','Celine Dion']],
 finalSong:[['See You Later, Alligator','Bill Haley & His Comets'],['Thank You','Dido'],["(I've Had) The Time of My Life",'Bill Medley & Jennifer Warnes'],['Throw Your Arms Around Me','Hunters & Collectors'],["We've Only Just Begun",'The Carpenters'],['We Go Together','Grease'],['Good Riddance (Time of Your Life)','Green Day'],["I'm on My Way",'The Proclaimers'],['December, 1963 (Oh, What a Night)','The Four Seasons'],['We Are Family','Sister Sledge'],['Wish You Well','Bernard Fanning'],['I Knew the Bride','Nick Lowe']]
};
let inspireType='entrance',shortlist=[],chosenSongs={entrance:'',bridal1:'',bridal2:'',bridal3:'',finalSong:''},songMedia={},activeAudio=null,activePreviewKey='';

function coverageState(){const c=checked('coverage'),whole=c.includes('Ceremony & Reception');return {c,hasCeremony:whole||c.includes('Ceremony'),hasReception:whole||c.includes('Reception')}}
function route(){const {c,hasCeremony,hasReception}=coverageState();if(!c.length)return [0,1,2,3,4,5];const r=[0];if(hasCeremony)r.push(1);if(hasReception)r.push(2);r.push(3,4,5);return r}
function smartLogic(){
 const {hasCeremony,hasReception}=coverageState();
 const whole=form.querySelector('#both'),cer=form.querySelector('#ceremony'),rec=form.querySelector('#reception');if(whole.checked){cer.checked=false;rec.checked=false}
 const later=form.querySelector('#ceremonyLater'),cerNeeds=[...form.querySelectorAll('[name="ceremonyNeeds"]:not(#ceremonyLater)')];if(later.checked)cerNeeds.forEach(x=>x.checked=false);
 const receptionLater=form.querySelector('#receptionLater'),receptionSpecific=[...form.querySelectorAll('[name="receptionNeeds"]:not(#receptionLater)')];if(receptionLater?.checked)receptionSpecific.forEach(x=>x.checked=false);
 const micAlready=form.querySelector('#ceremonyMic')?.checked||form.querySelector('#speeches')?.checked;
 const micExtra=document.querySelector('#wirelessExtraChoice'),micInput=form.querySelector('#wireless');if(micExtra){micExtra.style.display=micAlready?'none':'';if(micAlready)micInput.checked=false}
 const karaokeAlready=form.querySelector('#receptionKaraoke')?.checked,karaokeExtra=form.querySelector('#karaokeExtra')?.closest('.choice');if(karaokeExtra){karaokeExtra.style.display=karaokeAlready?'none':'';if(karaokeAlready)form.querySelector('#karaokeExtra').checked=false}
 const note=document.querySelector('#smartExtrasNote');if(note){const notes=[];if(micAlready)notes.push('Microphone support is already covered by your earlier selections.');if(karaokeAlready)notes.push('Karaoke is already included in your reception selections.');note.textContent=notes.join(' ')}
 const music=document.querySelector('#smartMusicDetails');if(music){const other=form.querySelector('#mOther')?.checked,old=form.elements.otherMusic?.value||'';music.innerHTML=other?`<label class="wedField wide"><span>What else do you enjoy? <small style="font-weight:400;color:#7f8b9d">(optional)</small></span><input name="otherMusic" value="${esc(old)}" placeholder="Genre, era, artists or the general vibe"></label>`:''}
 if(!hasCeremony)form.querySelectorAll('[name="ceremonyNeeds"]').forEach(x=>x.checked=false);if(!hasReception)form.querySelectorAll('[name="receptionNeeds"]').forEach(x=>x.checked=false);
}
function show(target,shouldScroll=true){smartLogic();const r=route();if(!r.includes(target)){const nv=r.find(i=>i>target);target=nv===undefined?r[r.length-1]:nv}step=target;const pos=r.indexOf(step);steps.forEach((x,i)=>x.classList.toggle('active',i===step));bars.forEach((x,i)=>{const rp=r.indexOf(i);x.style.display=rp===-1?'none':'';x.classList.toggle('on',rp!==-1&&rp<=pos)});prev.style.visibility=pos>0?'visible':'hidden';next.innerHTML=pos===r.length-1?'Continue to wedding enquiry <span>→</span>':'Next step <span>→</span>';if(pos===r.length-1)summary();if(shouldScroll)window.scrollTo({top:Math.max(0,document.querySelector('.wedProgress').offsetTop-120),behavior:'smooth'})}
function timeline(){return [...document.querySelectorAll('.timelineRow')].map(r=>{const i=r.querySelectorAll('input');return {time:i[0].value,event:i[1].value.trim()}}).filter(x=>x.time||x.event)}
function data(){const {hasCeremony,hasReception}=coverageState();return {date:form.elements.date.value,venue:form.elements.venue.value.trim(),guests:form.elements.guests.value,setting:form.elements.setting.value,coverage:checked('coverage'),ceremonyNeeds:hasCeremony?checked('ceremonyNeeds'):[],receptionNeeds:hasReception?checked('receptionNeeds'):[],musicStyles:checked('musicStyles'),otherMusic:form.elements.otherMusic?.value.trim()||'',musicControl:checked('musicControl')[0]||'',mustPlay:form.elements.mustPlay.value.trim(),wouldLove:form.elements.wouldLove.value.trim(),doNotPlay:form.elements.doNotPlay.value.trim(),extras:checked('extras'),timeline:timeline(),songShortlist:shortlist,chosenSongs:{...chosenSongs}}}
function summary(){const d=data(),{hasCeremony,hasReception}=coverageState(),items=[['Wedding',d.coverage.join(', ')||'Not decided yet'],['Date',d.date||'Not decided yet'],['Venue',d.venue||'Not decided yet'],['Guests',d.guests?`Approx. ${d.guests}`:'Not decided yet']];if(hasCeremony)items.push(['Ceremony',d.ceremonyNeeds.join(', ')||'Not specified']);if(hasReception)items.push(['Reception support',d.receptionNeeds.join(', ')||'None selected']);items.push(['Music',d.musicStyles.join(', ')||'Not specified']);if(d.otherMusic)items.push(['Other music',d.otherMusic]);items.push(['Music direction',d.musicControl||'Not decided yet']);if(d.mustPlay)items.push(['Must play',d.mustPlay]);if(d.doNotPlay)items.push(['Do not play',d.doNotPlay]);if(d.songShortlist?.length)items.push(['Saved song ideas',d.songShortlist.join(' · ')]);Object.entries(d.chosenSongs||{}).forEach(([k,v])=>{if(v)items.push([{entrance:'Entrance song',bridal1:'1st Bridal Waltz',bridal2:'2nd Bridal Waltz',bridal3:'3rd Bridal Waltz',finalSong:'Final song / farewell'}[k],v])});items.push(['Extras',d.extras.join(', ')||'None selected']);document.querySelector('#wedSummary').innerHTML=items.map(([a,b])=>`<div class="summaryCard"><small>${a}</small><strong>${b}</strong></div>`).join('')}
function removeTextFrom(fieldName,text){const field=form.elements[fieldName];if(!field)return;field.value=field.value.split('\n').map(x=>x.trim()).filter(x=>x&&x!==text).join('\n')}
function addTextTo(fieldName,text){const field=form.elements[fieldName];if(!field)return;const lines=field.value.split('\n').map(x=>x.trim()).filter(Boolean);if(!lines.includes(text))lines.push(text);field.value=lines.join('\n')}
function choiceText(type,text){const labels={entrance:'Entrance',bridal1:'1st Bridal Waltz',bridal2:'2nd Bridal Waltz',bridal3:'3rd Bridal Waltz',finalSong:'Final song'};return `${labels[type]||'Song'}: ${text}`}
function choiceField(type){return type.startsWith('bridal')?'mustPlay':'wouldLove'}
function renderShortlist(){const box=document.querySelector('#shortlistItems');if(!box)return;box.innerHTML=shortlist.length?shortlist.map((x,i)=>`<span class="shortChip">${esc(x)} <button type="button" data-remove-short="${i}" aria-label="Remove saved song idea">×</button></span>`).join(''):'<span style="color:#77859a">No song ideas saved yet.</span>'}
function mediaKey(type,i){return `${type}:${i}`}
function placeholderArt(){return 'data:image/svg+xml;charset=UTF-8,'+encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" width="120" height="120"><defs><linearGradient id="g" x1="0" y1="0" x2="1" y2="1"><stop stop-color="#ef37ff"/><stop offset="1" stop-color="#46ddff"/></linearGradient></defs><rect width="120" height="120" rx="18" fill="#0b0f16"/><circle cx="60" cy="60" r="35" fill="url(#g)" opacity=".28"/><text x="60" y="73" text-anchor="middle" font-size="42" fill="white">♫</text></svg>`)}
function renderIdeas(){const list=document.querySelector('#inspireList');if(!list)return;list.innerHTML=songIdeas[inspireType].map(([song,artist],i)=>{const text=`${song} — ${artist}`,saved=shortlist.includes(text),chosen=chosenSongs[inspireType]===text,m=songMedia[mediaKey(inspireType,i)]||{};return `<div class="inspireSong"><img class="songArt" data-art="${i}" src="${esc(m.artwork||placeholderArt())}" alt="${esc(song)} artwork"><div class="songInfo"><strong>${esc(song)}</strong><small>${esc(artist)}</small></div><div class="songActions"><button type="button" data-preview="${i}" class="${m.unavailable?'previewUnavailable':''}" ${m.unavailable?'disabled':''}>${activePreviewKey===mediaKey(inspireType,i)?'⏸ Pause':m.unavailable?'Preview unavailable':'▶ Preview'}</button><button type="button" data-short="${i}" class="${saved?'isOn':''}">${saved?'♥ Saved':'♡ Save idea'}</button><button type="button" data-add="${i}" class="${chosen?'isOn':''}">${chosen?'✓ Chosen':'＋ Choose'}</button></div></div>`}).join('');loadVisibleMedia()}
async function loadMedia(type,i){const key=mediaKey(type,i);if(songMedia[key])return songMedia[key];const [song,artist]=songIdeas[type][i];try{const term=encodeURIComponent(`${song} ${artist}`),url=`https://itunes.apple.com/search?term=${term}&country=AU&media=music&entity=song&limit=8`;const r=await fetch(url);if(!r.ok)throw new Error('lookup failed');const j=await r.json(),norm=x=>(x||'').toLowerCase().replace(/[^a-z0-9]/g,'');const result=(j.results||[]).find(x=>norm(x.trackName)===norm(song)&&norm(x.artistName).includes(norm(artist.split(' / ')[0]).slice(0,8)))||(j.results||[])[0];songMedia[key]=result?{preview:result.previewUrl||'',artwork:(result.artworkUrl100||'').replace('100x100bb','200x200bb'),storeUrl:result.trackViewUrl||'',unavailable:!result.previewUrl}:{unavailable:true};}catch(e){songMedia[key]={unavailable:true}}return songMedia[key]}
async function loadVisibleMedia(){const type=inspireType;await Promise.all(songIdeas[type].map((_,i)=>loadMedia(type,i)));if(type===inspireType)renderIdeasNoLoad()}
function renderIdeasNoLoad(){const list=document.querySelector('#inspireList');if(!list)return;list.innerHTML=songIdeas[inspireType].map(([song,artist],i)=>{const text=`${song} — ${artist}`,saved=shortlist.includes(text),chosen=chosenSongs[inspireType]===text,m=songMedia[mediaKey(inspireType,i)]||{};return `<div class="inspireSong"><img class="songArt" src="${esc(m.artwork||placeholderArt())}" alt="${esc(song)} artwork"><div class="songInfo"><strong>${esc(song)}</strong><small>${esc(artist)}</small></div><div class="songActions"><button type="button" data-preview="${i}" class="${m.unavailable?'previewUnavailable':''}" ${m.unavailable?'disabled':''}>${activePreviewKey===mediaKey(inspireType,i)?'⏸ Pause':m.unavailable?'Preview unavailable':'▶ Preview'}</button><button type="button" data-short="${i}" class="${saved?'isOn':''}">${saved?'♥ Saved':'♡ Save idea'}</button><button type="button" data-add="${i}" class="${chosen?'isOn':''}">${chosen?'✓ Chosen':'＋ Choose'}</button></div></div>`}).join('')}
function stopPreview(){if(activeAudio){activeAudio.pause();activeAudio.currentTime=0}activeAudio=null;activePreviewKey='';renderIdeasNoLoad()}
async function togglePreview(i){const key=mediaKey(inspireType,i);if(activePreviewKey===key){stopPreview();return}const m=await loadMedia(inspireType,i);if(!m.preview){renderIdeasNoLoad();return}if(activeAudio){activeAudio.pause();activeAudio.currentTime=0}activeAudio=new Audio(m.preview);activePreviewKey=key;activeAudio.addEventListener('ended',()=>{activeAudio=null;activePreviewKey='';renderIdeasNoLoad()},{once:true});activeAudio.addEventListener('error',()=>{songMedia[key].unavailable=true;activeAudio=null;activePreviewKey='';renderIdeasNoLoad()},{once:true});try{await activeAudio.play()}catch(e){songMedia[key].unavailable=true;activeAudio=null;activePreviewKey=''}renderIdeasNoLoad()}
const inspire=document.querySelector('#songInspiration'),toggle=document.querySelector('#toggleInspiration');toggle?.addEventListener('click',()=>{inspire.classList.toggle('open');toggle.textContent=inspire.classList.contains('open')?'Hide song ideas':'Browse song ideas';renderIdeas();renderShortlist()});
document.querySelectorAll('.inspireTab').forEach(b=>b.addEventListener('click',()=>{stopPreview();document.querySelectorAll('.inspireTab').forEach(x=>x.classList.remove('active'));b.classList.add('active');inspireType=b.dataset.inspire;renderIdeas()}));
document.querySelector('#shortlistItems')?.addEventListener('click',e=>{const b=e.target.closest('[data-remove-short]');if(!b)return;shortlist.splice(Number(b.dataset.removeShort),1);renderShortlist();renderIdeasNoLoad()});
document.querySelector('#inspireList')?.addEventListener('click',async e=>{const preview=e.target.closest('[data-preview]'),save=e.target.closest('[data-short]'),choose=e.target.closest('[data-add]');if(preview)return togglePreview(Number(preview.dataset.preview));const btn=save||choose;if(!btn)return;const [song,artist]=songIdeas[inspireType][Number(btn.dataset.short??btn.dataset.add)],text=`${song} — ${artist}`;if(save){const at=shortlist.indexOf(text);if(at>=0)shortlist.splice(at,1);else shortlist.push(text);renderShortlist();renderIdeasNoLoad();return}const old=chosenSongs[inspireType];if(old===text){removeTextFrom(choiceField(inspireType),choiceText(inspireType,text));chosenSongs[inspireType]=''}else{if(old)removeTextFrom(choiceField(inspireType),choiceText(inspireType,old));chosenSongs[inspireType]=text;addTextTo(choiceField(inspireType),choiceText(inspireType,text))}renderIdeasNoLoad()});
function addTimelineMoment(label){const rows=[...document.querySelectorAll('.timelineRow')];let row=rows.find(r=>!r.querySelectorAll('input')[1].value.trim());if(!row){row=document.createElement('div');row.className='timelineRow';row.innerHTML='<input type="time" aria-label="Timeline time"><input aria-label="Timeline event"><button type="button" class="removeRow" aria-label="Remove row">×</button>';document.querySelector('#timeline').appendChild(row)}row.querySelectorAll('input')[1].value=label==='Custom Moment'?'':label;row.querySelectorAll('input')[1].focus()}
document.querySelector('#timelinePresets')?.addEventListener('click',e=>{const b=e.target.closest('.timelinePreset');if(b)addTimelineMoment(b.textContent.trim())});
prev.addEventListener('click',()=>{const r=route(),pos=r.indexOf(step);if(pos>0)show(r[pos-1])});
next.addEventListener('click',()=>{const r=route(),pos=r.indexOf(step);if(pos<r.length-1)return show(r[pos+1]);const d=data();localStorage.setItem('ozzsoundWeddingBuilder',JSON.stringify(d));location.href='event-enquiry.html?event=Wedding&from=wedding'});
form.addEventListener('change',e=>{if(e.target.name==='coverage'){if(e.target.id==='both'&&e.target.checked){form.querySelector('#ceremony').checked=false;form.querySelector('#reception').checked=false}else if((e.target.id==='ceremony'||e.target.id==='reception')&&e.target.checked)form.querySelector('#both').checked=false}if(e.target.name==='ceremonyNeeds'){if(e.target.id==='ceremonyLater'&&e.target.checked)form.querySelectorAll('[name="ceremonyNeeds"]:not(#ceremonyLater)').forEach(x=>x.checked=false);else if(e.target.checked)form.querySelector('#ceremonyLater').checked=false}if(e.target.name==='receptionNeeds'){if(e.target.id==='receptionLater'&&e.target.checked)form.querySelectorAll('[name="receptionNeeds"]:not(#receptionLater)').forEach(x=>x.checked=false);else if(e.target.checked)form.querySelector('#receptionLater').checked=false}smartLogic();if(e.target.name==='coverage')show(step)});
document.querySelector('#addTimeline').addEventListener('click',()=>{const row=document.createElement('div');row.className='timelineRow';row.innerHTML='<input type="time" aria-label="Timeline time"><input placeholder="e.g. 1st Bridal Waltz" aria-label="Timeline event"><button type="button" class="removeRow" aria-label="Remove row">×</button>';document.querySelector('#timeline').appendChild(row)});document.querySelector('#timeline').addEventListener('click',e=>{if(e.target.closest('.removeRow')&&document.querySelectorAll('.timelineRow').length>1)e.target.closest('.timelineRow').remove()});
try{const saved=JSON.parse(localStorage.getItem('ozzsoundWeddingBuilder')||'null');if(saved){if(saved.date)form.elements.date.value=saved.date;if(saved.venue)form.elements.venue.value=saved.venue;if(saved.guests)form.elements.guests.value=saved.guests;if(saved.setting)form.elements.setting.value=saved.setting;const restoreChecks=(name,vals)=>{(vals||[]).forEach(v=>{const el=[...form.querySelectorAll('[name="'+name+'"]')].find(x=>x.value===v);if(el)el.checked=true})};restoreChecks('coverage',saved.coverage);restoreChecks('ceremonyNeeds',saved.ceremonyNeeds);restoreChecks('receptionNeeds',saved.receptionNeeds);restoreChecks('musicStyles',saved.musicStyles);restoreChecks('extras',saved.extras);const mc=[...form.querySelectorAll('[name="musicControl"]')].find(x=>x.value===saved.musicControl);if(mc)mc.checked=true;form.elements.mustPlay.value=saved.mustPlay||'';form.elements.wouldLove.value=saved.wouldLove||'';form.elements.doNotPlay.value=saved.doNotPlay||'';shortlist=Array.isArray(saved.songShortlist)?saved.songShortlist:[];chosenSongs={...chosenSongs,...(saved.chosenSongs||{})};if(Array.isArray(saved.timeline)&&saved.timeline.length){const host=document.querySelector('#timeline');host.innerHTML='';saved.timeline.forEach(x=>{const row=document.createElement('div');row.className='timelineRow';row.innerHTML='<input type="time" aria-label="Timeline time"><input aria-label="Timeline event"><button type="button" class="removeRow" aria-label="Remove row">×</button>';const inputs=row.querySelectorAll('input');inputs[0].value=x.time||'';inputs[1].value=x.event||'';host.appendChild(row)})}}}catch(e){console.warn('Could not restore wedding builder',e)}
const carriedDate=new URLSearchParams(location.search).get('date')||(()=>{try{return sessionStorage.getItem('ozzsoundSelectedDate')||''}catch(e){return''}})();if(/^\d{4}-\d{2}-\d{2}$/.test(carriedDate)&&form.elements.date){form.elements.date.value=carriedDate;try{localStorage.setItem('ozzsoundWeddingBuilder',JSON.stringify(data()))}catch(e){}}
show(0,false);
})();
