(()=>{
const form=document.querySelector('#weddingBuilder');if(!form)return;
const steps=[...document.querySelectorAll('.wedStep')],bars=[...document.querySelectorAll('.wedProgress span')],prev=document.querySelector('#wedPrev'),next=document.querySelector('#wedNext');let step=0;
const today=new Date(),date=form.elements.date;date.min=`${today.getFullYear()}-${String(today.getMonth()+1).padStart(2,'0')}-${String(today.getDate()).padStart(2,'0')}`;
const checked=name=>[...form.querySelectorAll(`[name="${name}"]:checked`)].map(x=>x.value);
const esc=v=>(v||'').replace(/&/g,'&amp;').replace(/"/g,'&quot;').replace(/</g,'&lt;');
const songIdeas={
 entrance:[['Signed, Sealed, Delivered','Stevie Wonder'],['Walking on Sunshine','Katrina & The Waves'],['Another One Bites the Dust','Queen'],['From This Moment On','Shania Twain'],['Love and Marriage','Frank Sinatra'],['I Do, I Do, I Do, I Do, I Do','ABBA'],['Can You Feel the Love Tonight','Elton John'],["I'm a Believer",'Smash Mouth'],['Beautiful Day','U2'],["You're the One That I Want",'Grease'],['Chapel of Love','The Dixie Cups'],['Love Today','Mika'],['Love Is in the Air','John Paul Young'],['2 Be Loved','Lizzo']],
 firstDance:[['At Last','Etta James'],['Could I Have This Dance','Anne Murray'],["Can't Help Falling in Love",'Elvis Presley'],['Unchained Melody','The Righteous Brothers'],['Unforgettable','Natalie Cole'],['Everything','Michael Bublé'],['Endless Love','Lionel Richie & Diana Ross'],['Perfect','Ed Sheeran / Beyoncé'],['The Power of Love','Celine Dion'],['A Thousand Years','Christina Perri'],['When a Man Loves a Woman','Percy Sledge'],['Lover','Taylor Swift'],['Amazed','Lonestar'],['Until I Found You','Stephen Sanchez'],['When You Say Nothing at All','Ronan Keating'],['You Are the Reason','Calum Scott'],['I Knew I Loved You','Savage Garden'],['I Get to Love You','Ruelle'],['Truly Madly Deeply','Savage Garden'],['From This Moment On','Shania Twain'],['Have I Told You Lately','Van Morrison'],['Heaven','Bryan Adams'],['Still the One','Shania Twain'],['Because You Loved Me','Celine Dion']],
 finalSong:[['See You Later, Alligator','Bill Haley & His Comets'],['Thank You','Dido'],["(I've Had) The Time of My Life",'Bill Medley & Jennifer Warnes'],['Throw Your Arms Around Me','Hunters & Collectors'],["We've Only Just Begun",'The Carpenters'],['We Go Together','Grease'],['Good Riddance (Time of Your Life)','Green Day'],["I'm on My Way",'The Proclaimers'],['December, 1963 (Oh, What a Night)','The Four Seasons'],['We Are Family','Sister Sledge'],['Wish You Well','Bernard Fanning'],['I Knew the Bride','Nick Lowe']]
};
let inspireType='entrance',shortlist=[];

function coverageState(){const c=checked('coverage'),whole=c.includes('Ceremony & Reception');return {c,hasCeremony:whole||c.includes('Ceremony'),hasReception:whole||c.includes('Reception')}}
function route(){const {c,hasCeremony,hasReception}=coverageState();if(!c.length)return [0,1,2,3,4,5];const r=[0];if(hasCeremony)r.push(1);if(hasReception)r.push(2);r.push(3,4,5);return r}
function smartLogic(){
 const {hasCeremony,hasReception}=coverageState();
 const whole=form.querySelector('#both'),cer=form.querySelector('#ceremony'),rec=form.querySelector('#reception');if(whole.checked){cer.checked=false;rec.checked=false}
 const later=form.querySelector('#ceremonyLater'),cerNeeds=[...form.querySelectorAll('[name="ceremonyNeeds"]:not(#ceremonyLater)')];if(later.checked)cerNeeds.forEach(x=>x.checked=false);
 const receptionLater=form.querySelector('#receptionLater'),receptionSpecific=[...form.querySelectorAll('[name="receptionNeeds"]:not(#receptionLater)')];if(receptionLater?.checked)receptionSpecific.forEach(x=>x.checked=false);
 const micAlready=form.querySelector('#ceremonyMic')?.checked||form.querySelector('#speeches')?.checked;
 const micExtra=document.querySelector('#wirelessExtraChoice'),micInput=form.querySelector('#wireless');if(micExtra){micExtra.style.display=micAlready?'none':'';if(micAlready)micInput.checked=false}
 const karaokeAlready=form.querySelector('#receptionKaraoke')?.checked,karaokeExtra=form.querySelector('#karaokeExtra')?.closest('.choice');if(karaokeExtra){karaokeExtra.style.display=karaokeAlready?'none':'';if(karaokeAlready)form.querySelector('#karaokeExtra').checked=false}
 const note=document.querySelector('#smartExtrasNote');if(note){const notes=[];if(micAlready)notes.push('Microphone support is already covered by your earlier selections.');if(karaokeAlready)notes.push('Karaoke is already included in your reception selections.');note.textContent=notes.join(' ')}
 const music=document.querySelector('#smartMusicDetails');if(music){const other=form.querySelector('#mOther')?.checked,old=form.elements.otherMusic?.value||'';music.innerHTML=other?`<label class="wedField wide"><span>What else do you enjoy? <small style="font-weight:400;color:#7f8b9d">(optional)</small></span><input name="otherMusic" value="${esc(old)}" placeholder="Genre, era, artists or the general vibe"></label>`:''}
 if(!hasCeremony)form.querySelectorAll('[name="ceremonyNeeds"]').forEach(x=>x.checked=false);if(!hasReception)form.querySelectorAll('[name="receptionNeeds"]').forEach(x=>x.checked=false);
}
function show(target){smartLogic();const r=route();if(!r.includes(target)){const nv=r.find(i=>i>target);target=nv===undefined?r[r.length-1]:nv}step=target;const pos=r.indexOf(step);steps.forEach((x,i)=>x.classList.toggle('active',i===step));bars.forEach((x,i)=>{const rp=r.indexOf(i);x.style.display=rp===-1?'none':'';x.classList.toggle('on',rp!==-1&&rp<=pos)});prev.style.visibility=pos>0?'visible':'hidden';next.innerHTML=pos===r.length-1?'Continue to wedding enquiry <span>→</span>':'Next step <span>→</span>';if(pos===r.length-1)summary();window.scrollTo({top:Math.max(0,document.querySelector('.wedProgress').offsetTop-120),behavior:'smooth'})}
function timeline(){return [...document.querySelectorAll('.timelineRow')].map(r=>{const i=r.querySelectorAll('input');return {time:i[0].value,event:i[1].value.trim()}}).filter(x=>x.time||x.event)}
function data(){const {hasCeremony,hasReception}=coverageState();return {date:form.elements.date.value,venue:form.elements.venue.value.trim(),guests:form.elements.guests.value,setting:form.elements.setting.value,coverage:checked('coverage'),ceremonyNeeds:hasCeremony?checked('ceremonyNeeds'):[],receptionNeeds:hasReception?checked('receptionNeeds'):[],musicStyles:checked('musicStyles'),otherMusic:form.elements.otherMusic?.value.trim()||'',musicControl:checked('musicControl')[0]||'',mustPlay:form.elements.mustPlay.value.trim(),wouldLove:form.elements.wouldLove.value.trim(),doNotPlay:form.elements.doNotPlay.value.trim(),extras:checked('extras'),timeline:timeline(),songShortlist:shortlist}}
function summary(){const d=data(),{hasCeremony,hasReception}=coverageState(),items=[['Wedding',d.coverage.join(', ')||'Not decided yet'],['Date',d.date||'Not decided yet'],['Venue',d.venue||'Not decided yet'],['Guests',d.guests?`Approx. ${d.guests}`:'Not decided yet']];if(hasCeremony)items.push(['Ceremony',d.ceremonyNeeds.join(', ')||'Not specified']);if(hasReception)items.push(['Reception support',d.receptionNeeds.join(', ')||'None selected']);items.push(['Music',d.musicStyles.join(', ')||'Not specified']);if(d.otherMusic)items.push(['Other music',d.otherMusic]);items.push(['Music direction',d.musicControl||'Not decided yet']);if(d.mustPlay)items.push(['Must play',d.mustPlay]);if(d.doNotPlay)items.push(['Do not play',d.doNotPlay]);if(d.songShortlist?.length)items.push(['Song shortlist',d.songShortlist.join(' · ')]);items.push(['Extras',d.extras.join(', ')||'None selected']);document.querySelector('#wedSummary').innerHTML=items.map(([a,b])=>`<div class="summaryCard"><small>${a}</small><strong>${b}</strong></div>`).join('')}
function addTextTo(fieldName,text){const field=form.elements[fieldName];if(!field)return;const lines=field.value.split('\n').map(x=>x.trim()).filter(Boolean);if(!lines.includes(text))lines.push(text);field.value=lines.join('\n')}
function renderShortlist(){const box=document.querySelector('#shortlistItems');if(!box)return;box.innerHTML=shortlist.length?shortlist.map(x=>`<span class="shortChip">${esc(x)}</span>`).join(''):'<span style="color:#77859a">No songs shortlisted yet.</span>'}
function renderIdeas(){const list=document.querySelector('#inspireList');if(!list)return;list.innerHTML=songIdeas[inspireType].map(([song,artist],i)=>`<div class="inspireSong"><span><strong>${esc(song)}</strong><br><small>${esc(artist)}</small></span><span><button type="button" data-short="${i}">❤️ Shortlist</button> <button type="button" data-add="${i}">＋ Add</button></span></div>`).join('')}
const inspire=document.querySelector('#songInspiration'),toggle=document.querySelector('#toggleInspiration');toggle?.addEventListener('click',()=>{inspire.classList.toggle('open');toggle.textContent=inspire.classList.contains('open')?'Hide song ideas':'Browse song ideas';renderIdeas();renderShortlist()});
document.querySelectorAll('.inspireTab').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.inspireTab').forEach(x=>x.classList.remove('active'));b.classList.add('active');inspireType=b.dataset.inspire;renderIdeas()}));
document.querySelector('#inspireList')?.addEventListener('click',e=>{const short=e.target.closest('[data-short]'),add=e.target.closest('[data-add]');const btn=short||add;if(!btn)return;const [song,artist]=songIdeas[inspireType][Number(btn.dataset.short??btn.dataset.add)],text=`${song} — ${artist}`;if(short){if(!shortlist.includes(text))shortlist.push(text);renderShortlist();return}if(inspireType==='firstDance')addTextTo('mustPlay',text);else if(inspireType==='entrance')addTextTo('wouldLove',`Entrance: ${text}`);else addTextTo('wouldLove',`Final song: ${text}`);btn.textContent='✓ Added'});
function addTimelineMoment(label){const rows=[...document.querySelectorAll('.timelineRow')];let row=rows.find(r=>!r.querySelectorAll('input')[1].value.trim());if(!row){row=document.createElement('div');row.className='timelineRow';row.innerHTML='<input type="time" aria-label="Timeline time"><input aria-label="Timeline event"><button type="button" class="removeRow" aria-label="Remove row">×</button>';document.querySelector('#timeline').appendChild(row)}row.querySelectorAll('input')[1].value=label==='Custom Moment'?'':label;row.querySelectorAll('input')[1].focus()}
document.querySelector('#timelinePresets')?.addEventListener('click',e=>{const b=e.target.closest('.timelinePreset');if(b)addTimelineMoment(b.textContent.trim())});
prev.addEventListener('click',()=>{const r=route(),pos=r.indexOf(step);if(pos>0)show(r[pos-1])});
next.addEventListener('click',()=>{const r=route(),pos=r.indexOf(step);if(pos<r.length-1)return show(r[pos+1]);const d=data();localStorage.setItem('ozzsoundWeddingBuilder',JSON.stringify(d));location.href='index.html?from=wedding#contact'});
form.addEventListener('change',e=>{if(e.target.name==='coverage'){if(e.target.id==='both'&&e.target.checked){form.querySelector('#ceremony').checked=false;form.querySelector('#reception').checked=false}else if((e.target.id==='ceremony'||e.target.id==='reception')&&e.target.checked)form.querySelector('#both').checked=false}if(e.target.name==='ceremonyNeeds'){if(e.target.id==='ceremonyLater'&&e.target.checked)form.querySelectorAll('[name="ceremonyNeeds"]:not(#ceremonyLater)').forEach(x=>x.checked=false);else if(e.target.checked)form.querySelector('#ceremonyLater').checked=false}if(e.target.name==='receptionNeeds'){if(e.target.id==='receptionLater'&&e.target.checked)form.querySelectorAll('[name="receptionNeeds"]:not(#receptionLater)').forEach(x=>x.checked=false);else if(e.target.checked)form.querySelector('#receptionLater').checked=false}smartLogic();if(e.target.name==='coverage')show(step)});
document.querySelector('#addTimeline').addEventListener('click',()=>{const row=document.createElement('div');row.className='timelineRow';row.innerHTML='<input type="time" aria-label="Timeline time"><input placeholder="e.g. First dance" aria-label="Timeline event"><button type="button" class="removeRow" aria-label="Remove row">×</button>';document.querySelector('#timeline').appendChild(row)});document.querySelector('#timeline').addEventListener('click',e=>{if(e.target.closest('.removeRow')&&document.querySelectorAll('.timelineRow').length>1)e.target.closest('.timelineRow').remove()});show(0);
})();
