(()=>{
'use strict';
if(window.__OZZSOUND_ADMIN_ISSUES__)return;window.__OZZSOUND_ADMIN_ISSUES__=true;
const cfg=window.OZZSOUND_CONFIG||{};let db=null,count=0;
const style=document.createElement('style');style.textContent=`.issues-reported-tab{position:relative}.issues-reported-count{display:inline-grid;place-items:center;min-width:20px;height:20px;padding:0 5px;margin-left:6px;border-radius:999px;background:#ff35c9;color:white;font-size:11px;font-weight:900}.website-issue-badge{display:inline-flex;margin-top:7px;padding:6px 9px;border:1px solid rgba(255,89,210,.48);border-radius:999px;background:rgba(255,48,196,.1);color:#ffd1f4;font-size:11px;font-weight:900;text-transform:uppercase}`;document.head.appendChild(style);
function getDb(){if(window.OZZSOUND_ADMIN_CLIENT)return window.OZZSOUND_ADMIN_CLIENT;if(window.supabase&&cfg.supabaseUrl&&cfg.supabasePublishableKey)return window.supabase.createClient(cfg.supabaseUrl,cfg.supabasePublishableKey);return null}
function ensureTab(){if(document.getElementById('issuesReportedTab'))return;const settings=[...document.querySelectorAll('button,a')].find(x=>/^Settings$/i.test((x.textContent||'').trim()));if(!settings)return;const tab=document.createElement(settings.tagName.toLowerCase());tab.id='issuesReportedTab';tab.type='button';tab.className=settings.className+' issues-reported-tab';tab.innerHTML='Issues Reported <span class="issues-reported-count">'+count+'</span>';settings.parentElement.insertBefore(tab,settings);tab.addEventListener('click',openIssues)}
function openIssues(){const enquiries=[...document.querySelectorAll('button,a')].find(x=>/^Enquiries$/i.test((x.textContent||'').trim()));enquiries?.click();setTimeout(()=>{const search=document.querySelector('#searchInput,input[placeholder*="Search customer"]');if(search){search.value='Website Issue';search.dispatchEvent(new Event('input',{bubbles:true}));search.dispatchEvent(new Event('change',{bubbles:true}))}const heading=[...document.querySelectorAll('h1,h2')].find(x=>/^Enquiries$/i.test((x.textContent||'').trim()));if(heading)heading.textContent='Issues Reported';},120)}
async function refresh(){db=db||getDb();if(!db)return;const {data,error}=await db.from('enquiries').select('id,enquiry_ref,enquiry_type,status,admin_attention').eq('enquiry_type','issue_report');if(error)return;count=(data||[]).filter(x=>x.admin_attention!==false).length;const badge=document.querySelector('#issuesReportedTab .issues-reported-count');if(badge)badge.textContent=String(count);document.querySelectorAll('button').forEach(open=>{if(!/^Open Enquiry$/i.test((open.textContent||'').trim()))return;let card=open;for(let i=0;i<7&&card;i++,card=card.parentElement){const txt=card.innerText||'';const ref=(txt.match(/OZZ-[A-Z0-9]+/i)||[])[0];if(!ref)continue;const row=(data||[]).find(x=>String(x.enquiry_ref).toUpperCase()===ref.toUpperCase());if(row&&!card.querySelector('.website-issue-badge')){const b=document.createElement('div');b.className='website-issue-badge';b.textContent='⚠ Website issue report';open.parentElement?.parentElement?.insertBefore(b,open.parentElement);break}}})}
const obs=new MutationObserver(()=>{ensureTab()});obs.observe(document.documentElement,{subtree:true,childList:true});ensureTab();let tries=0;const timer=setInterval(()=>{tries++;ensureTab();refresh();if(tries>40)clearInterval(timer)},500);setInterval(refresh,30000);
})();